### ISSUE TITLE
Please consider API standardization

### ISSUE THREAD

**Issue by wikiped** [SaelKimberly/rxls#1]
First of all - thank you for making a reader that can finally work with both XLSX an XLXB files. This is a long-awaited solution.

However, considering that the main 'target user-base' is made solely from those who already use either pandas or polars, it might be a good strategy to offer an API that is as close / familiar to the intended user as it only could be. This would probably make adoption of this promising project even easier / faster.

With this in mind, please consider the following suggestions:

1. Use `read` as main function name.
  `xl_scan` probably better reflectes what is happenning __inside__ the function, but `read` probably better reflects the __intention__ of the whole idea behind this `Reader` and it is the first verb used in the description of this package.

1. Since output of the main function can return very different types it might be a good idea to offer the user functions more explicitly reflecting intended result type: something like `read_to_pandas`, `read_to_polars`.

1. Use the same names for entities already used in pandas / polars.
- `header` instead of `head`
- `float_precision` instead of `frounding`
- `skip_rows` and `skip_rows_after_header` instead of `skip_rows` and `drop_rows`, which sound synonimous and are bound to be a cause of confusion.
- `n_rows` instead of `take_rows`

1. Avoid shortenning the terms where it might be difficult to remember the shortenning. I.e. `drop_cels` is short of `l` and the benefit is not obvious - it would be more natural to type `cells` than `cels`.

1. Perhaps `drop_cels` would be better named as `first_cell_regex` to reflect its actual intent, which is currently discribed with litterally these words:
    > ...cell, that matches this \[regex\], will be first non-empty cell...

1. Use `progress` or `show_progress` instead of `with_tqdm`, which exposes an imlementation detail, which might not be familiar to all users. This might be accompanied with `progress_kwargs` to allow finetuning the title, etc.

1. Use `filter_col` instead of `index_col`
  Based on the desciption:
    > Column, that defines, whether row must exist, or not...

    the intended use sounds like it is about filtering, and not about indexing - and this is bound to cause confusion with pandas / polars user where `index` is a very specific term / operation. See for reference description of `index_col` in `pandas.read_excel`.

1. Use `ignore_empty_rows` instead of `keep_rows` to better reflect the intent and as it is already used in arrows.

1. Use `dtypes` instead of `inferring`. And accept a `dict` similarly to pandas/polars, allowing dtype to be a type name (like `UTF8`) or one the of the `DtypeInferenceStrategy` enum values (like: `SAFE` | `DROP` | `REGEX` | `...` ).

For reference below is the summary of APIs used by pandas / polars / arrows for reading Excel and CSV files.

<details><summary>Read Excel API Summary</summary>
<p>

|[pandas.read_excel](https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html)|[polars.read_excel](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.read_excel.html#polars-read-excel)|[xlsx2csv_options](https://github.com/dilshod/xlsx2csv/blob/master/xlsx2csv.py#L153)|
|---|---|---|
|sheet_name|file|sheetid|
|header|sheet_id|sheetname|
|names|sheet_name|dateformat|
|index_col|xlsx2csv_options|timeformat|
|usecols|read_csv_options -> see: Read CSV API Summary|floatformat|
|dtype||quoting|
|engine||delimiter|
|converters||sheetdelimiter|
|true_values||skip_empty_lines|
|false_values||skip_trailing_columns|
|skiprows||hyperlinks|
|nrows||include_sheet_pattern|
|na_values||exclude_sheet_pattern|
|keep_default_na||exclude_hidden_sheets|
|na_filter||skip_hidden_rows|
|verbose|||
|parse_dates|||
|date_parser|||
|date_format|||
|thousands|||
|decimal|||
|comment|||
|skipfooter|||
|storage_options|||
|use_nullable_dtypes|||

</p>
</details>

<details><summary>Read CSV API Summary</summary>
<p>

|[polars.read_csv](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.read_csv.html#polars.read_csv)|[arrow_read_csv](https://arrow.apache.org/docs/python/generated/pyarrow.csv.read_csv.html#pyarrow.csv.read_csv)|[pandas.read_csv](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html)|
|---|---|---|
|batch_size|input_file|cache_dates|
|columns|read_options|chunksize|
|comment_char|&nbsp;&nbsp;&nbsp;&nbsp;use_threads|comment|
|dtypes|&nbsp;&nbsp;&nbsp;&nbsp;block_size|compression|
|encoding|&nbsp;&nbsp;&nbsp;&nbsp;skip_rows|converters|
|eol_char|&nbsp;&nbsp;&nbsp;&nbsp;skip_rows_after_names|date_parser|
|file|&nbsp;&nbsp;&nbsp;&nbsp;column_names|dayfirst|
|has_header|&nbsp;&nbsp;&nbsp;&nbsp;autogenerate_column_names|decimal|
|ignore_errors|&nbsp;&nbsp;&nbsp;&nbsp;encoding|delim_whitespace|
|infer_schema_length|parse_options|delimiter|
|low_memory|&nbsp;&nbsp;&nbsp;&nbsp;delimiter|dialect|
|missing_utf8_is_empty_string|&nbsp;&nbsp;&nbsp;&nbsp;quote_char|doublequote|
|n_rows|&nbsp;&nbsp;&nbsp;&nbsp;double_quote|dtype|
|n_threads|&nbsp;&nbsp;&nbsp;&nbsp;escape_char|encoding|
|new_columns|&nbsp;&nbsp;&nbsp;&nbsp;newlines_in_values|encoding_errors|
|null_values|&nbsp;&nbsp;&nbsp;&nbsp;ignore_empty_lines|engine|
|quote_char|&nbsp;&nbsp;&nbsp;&nbsp;invalid_row_handler|error_bad_lines|
|rechunk|convert_options|escapechar|
|row_count_name|&nbsp;&nbsp;&nbsp;&nbsp;check_utf8|false_values|
|row_count_offset|&nbsp;&nbsp;&nbsp;&nbsp;column_types|filepath_or_buffer|
|sample_size|&nbsp;&nbsp;&nbsp;&nbsp;null_values|float_precision|
|sep|&nbsp;&nbsp;&nbsp;&nbsp;true_values|header|
|skip_rows|&nbsp;&nbsp;&nbsp;&nbsp;false_values|index_col|
|skip_rows_after_header|&nbsp;&nbsp;&nbsp;&nbsp;decimal_point|infer_datetime_format|
|storage_options|&nbsp;&nbsp;&nbsp;&nbsp;strings_can_be_null|iterator|
|try_parse_dates|&nbsp;&nbsp;&nbsp;&nbsp;quoted_strings_can_be_null|keep_date_col|
|use_pyarrow|&nbsp;&nbsp;&nbsp;&nbsp;include_columns|keep_default_na|
||&nbsp;&nbsp;&nbsp;&nbsp;include_missing_columns|lineterminator|
||&nbsp;&nbsp;&nbsp;&nbsp;auto_dict_encode|low_memory|
||&nbsp;&nbsp;&nbsp;&nbsp;auto_dict_max_cardinality|mangle_dupe_cols|
||&nbsp;&nbsp;&nbsp;&nbsp;timestamp_parsers|memory_map|
||memory_pool|na_filter|
|||na_values|
|||names|
|||nrows|
|||on_bad_lines|
|||parse_dates|
|||prefix|
|||quotechar|
|||quoting|
|||sep|
|||skip_blank_lines|
|||skipfooter|
|||skipinitialspace|
|||skiprows|
|||squeeze|
|||storage_options|
|||thousands|
|||true_values|
|||usecols|
|||verbose|
|||warn_bad_lines|

</p>
</details>

**Comment by SaelKimberly** [comment]
Hello!

I think, you are absolutely right about API. I should take a look at this weekend.
Also, there is, actually, big update cycle coming soon!

**Comment by SaelKimberly** [comment]
There it is 🙂

All code was updated successful, excluding tests - they must be totally rewritten :)

Soon, I will update Readme to make it relevant to changes in API and dependencies.
